services:
  dagster-webserver:
    build: .
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w workspace.yaml
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      DAGSTER_HOME: /dagster_home
      DUCKDB_PATH: /app/local.duckdb
    volumes:
      - .:/app
      - ./deploy/dagster_home:/dagster_home

  dagster-daemon:
    build: .
    command: dagster-daemon run
    env_file:
      - ${ENV_FILE:-.env.local}
    environment:
      DAGSTER_HOME: /dagster_home
      DUCKDB_PATH: /app/local.duckdb
    volumes:
      - .:/app
      - ./deploy/dagster_home:/dagster_home
